# Generated by Django 5.0.7 on 2025-01-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='bloodbankprofile',
            options={'verbose_name': 'Blood Bank', 'verbose_name_plural': 'Blood Banks'},
        ),
        migrations.AlterModelOptions(
            name='consumerprofile',
            options={'verbose_name': 'Consumer', 'verbose_name_plural': 'Consumers'},
        ),
        migrations.AlterModelOptions(
            name='donorprofile',
            options={'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
        migrations.RemoveField(
            model_name='bloodbankprofile',
            name='blood_bank_name',
        ),
    ]
