# Generated by Django 5.0.7 on 2025-01-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_admin_options_alter_bloodbankprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='last_name',
        ),
    ]
