# Generated by Django 5.0.7 on 2025-01-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_staffprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='last_name',
        ),
    ]
