# Generated by Django 5.0.7 on 2025-01-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_donorprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='last_name',
        ),
    ]
