# Generated by Django 5.0.7 on 2025-01-27 17:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_consumerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to=users.models.store_license),
        ),
        migrations.AlterField(
            model_name='bloodbankprofile',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to=users.models.store_registration),
        ),
        migrations.AlterField(
            model_name='bloodbankprofile',
            name='tax_documents',
            field=models.FileField(blank=True, null=True, upload_to=users.models.store_tax),
        ),
    ]
