# Generated by Django 5.0.7 on 2025-02-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_bloodbankprofile_license_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodbankprofile',
            options={'verbose_name': 'Hospital', 'verbose_name_plural': 'hospitals'},
        ),
    ]
