# Generated by Django 5.0.7 on 2025-02-07 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_bloodbankprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='blood_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='users.bloodbankprofile'),
        ),
    ]
