# Generated by Django 5.0.7 on 2025-02-07 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_staffprofile_blood_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='blood_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='users.bloodbankprofile'),
        ),
    ]
