# Generated by Django 5.0.7 on 2025-01-31 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_bloodbankprofile_license_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A +ve'), ('A-', 'A -ve'), ('B+', 'B +ve'), ('B-', 'B -ve'), ('AB+', 'AB +ve'), ('AB-', 'AB -ve'), ('O+', 'O +ve'), ('O-', 'O -ve')], max_length=5)),
                ('volume_ml', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collection_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_bags', to='users.bloodbankprofile')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donated_bags', to='users.donorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('units_required', models.PositiveIntegerField()),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=10)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('diagnosis', models.TextField()),
                ('hospital_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('required_date', models.DateField()),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('allocated_blood_bags', models.ManyToManyField(blank=True, to='inventory.bloodbag')),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='users.bloodbankprofile')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='users.consumerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Blood Stock'), ('NEAR_EXPIRY', 'Near Expiry'), ('CRITICAL_SHORTAGE', 'Critical Shortage')], max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A +ve'), ('A-', 'A -ve'), ('B+', 'B +ve'), ('B-', 'B -ve'), ('AB+', 'AB +ve'), ('AB-', 'AB -ve'), ('O+', 'O +ve'), ('O-', 'O -ve')], max_length=5)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='users.bloodbankprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('COLLECTION', 'Blood Collection'), ('ALLOCATION', 'Blood Allocation'), ('TRANSFER', 'Blood Transfer'), ('DISPOSAL', 'Blood Disposal')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_location', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('blood_bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.bloodbag')),
            ],
        ),
    ]
