# Generated by Django 5.0.7 on 2025-02-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='diagnosis',
        ),
    ]
