# Generated by Django 5.0.7 on 2025-01-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='performer',
        ),
    ]
