# Generated by Django 5.0.7 on 2025-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stocktransaction_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbag',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A +ve'), ('A-', 'A -ve'), ('B+', 'B +ve'), ('B-', 'B -ve'), ('AB+', 'AB +ve'), ('AB-', 'AB -ve'), ('O+', 'O +ve'), ('O-', 'O -ve')], max_length=5),
        ),
        migrations.AlterField(
            model_name='inventoryalert',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A +ve'), ('A-', 'A -ve'), ('B+', 'B +ve'), ('B-', 'B -ve'), ('AB+', 'AB +ve'), ('AB-', 'AB -ve'), ('O+', 'O +ve'), ('O-', 'O -ve')], max_length=5),
        ),
    ]
