# Generated by Django 5.0.7 on 2025-02-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_bloodrequest_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A +ve'), ('A-', 'A -ve'), ('B+', 'B +ve'), ('B-', 'B -ve'), ('AB+', 'AB +ve'), ('AB-', 'AB -ve'), ('O+', 'O +ve'), ('O-', 'O -ve')], max_length=5),
        ),
    ]
