# Generated by Django 5.0.7 on 2025-02-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_bloodrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbag',
            name='barcode',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
