# Generated by Django 5.0.7 on 2024-12-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bloodrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='hospital',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
